FORMAT: 1A
HOST: http://localhost:8000

# Image-manager

Simple CRUD service for storing firmware image metadata and binaries


# Group Images

## Image Collection [/image/]

### List All Images [GET]

+ Request
    + Headers
            Authorization: Bearer JWT
        
        
+ Response 200 (application/json)
    + Body
        [
          {
            "created": "2018-02-08T12:25:11.979313+00:00",
            "hw_version": "1.0.0-revA",
            "confirmed": true,
            "label": "ExampleFW",
            "fw_version": "1.0.0-rc1",
            "sha1": "cf23df2207d99a74fbe169e3eba035e633b65d94",
            "id": "b60aa5e9-cbe6-4b51-b76c-08cf8273db07"
          },
          {
            "created": "2018-02-08T12:25:11.998107+00:00",
            "hw_version": "1.0.0-revA",
            "confirmed": false,
            "label": "ExampleFW",
            "fw_version": "1.0.0-rc1",
            "sha1": "cf23df2207d99a74fbe169e3eba035e633b65d94",
            "id": "51b39543-9de1-4751-9fe2-48c8d6038ba1"
          }
        ]


### Create a New Image [POST]

Creates a new image based on a JSON object containing the following metadata.

+ label (string) - An informative human-readable label
+ fw_version (string) - FW Semantic versioning info
+ hw_version (string) - HW Semantic versioning info
+ sha1 (string) - Expected SHA1 of the image binary, used for consistency

+ Request (application/json)
    + Headers
            Authorization: Bearer JWT
    
    + Body
        {
            "label": "FW_Example",
            "fw_version": "1.0.0",
            "hw_version": "1.0.0",
            "sha1": "cf23df2207d99a74fbe169e3eba035e633b65d94"
        }


+ Response 201 (application/json)
    + Headers
            Location: /image/asdasdasdasdasdas

    + Schema
    
            {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "id": "http://jsonschema.net",
                "type": "object",
                "properties": {
                    "label": {
                      "type": "string"
                    },
                    "published_at": {
                      "type": "string"
                    },
                    "url": {
                      "type": "string",
                      "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
                    }
                },
                "required": [ "label","published_at", "url" ]
            }


## Images [/image/{image_id}]

+ Parameters
    + image_id: `b60aa5e9-cbe6-4b51-b76c-08cf8273db07` (guid) - Unique ID

### Retrieve a single image metadata [GET]
+ Request
    + Headers
            Authorization: Bearer JWT

+ Response 200 (application/json)

           {
                "label": "FW_Example",
                "fw_version": "1.0.0",
                "hw_version": "1.0.0",
                "sha1": "cf23df2207d99a74fbe169e3eba035e633b65d94"
            }


### Delete [DELETE]
+ Request
    + Headers
            Authorization: Bearer JWT
            
+ Response 200


## Image Binaries [/image/{image_id}/binary]

+ Parameters
    + image_id: `b60aa5e9-cbe6-4b51-b76c-08cf8273db07` (guid) - Unique ID

### Retrieve a single image binary [GET]
+ Request
    + Headers
            Authorization: Bearer JWT

+ Response 200 (application/octet-stream)

### Delete [DELETE]
+ Request
    + Headers
            Authorization: Bearer JWT
            
+ Response 200

### Add binary to an existing image [POST]

+ Parameters
    + image_id: `51b39543-9de1-4751-9fe2-48c8d6038ba1` (guid) - Unique ID
    
    
    
+ Request (multipart/form-data;boundary=BOUNDARY)
    + Headers
            Authorization: Bearer JWT
            
    + Body
        
            --BOUNDARY
            Content-Disposition: form-data; name="image"; filename="image.hex"
            Content-Type: application/octet-stream

            0123456789
            --BOUNDARY--
            

+ Response 200

